### PR TITLE
Add support for deep link facet hack

### PR DESCRIPTION
**Pull request by JPrevost**

### CODE REVIEW

**Review by matt-bernhardt — APPROVED** [review]
Simple and straightforward. The only thing I'd ask is that you put a link in the PR description to whatever documentation we have around this hack - or some other way for us to remember what this does.

**Comment by JPrevost** [comment]
Ha. Good one. This is only described in an email... thoughts?

**Comment by JPrevost** [comment]
I'll see if I can explain it a bit better and update the commit message.

**Comment by matt-bernhardt** [comment]
Yeah, if it is only in email there may be little we can do. Go ahead and merge whenever you like... :shipit:

**Comment by JPrevost** [comment]
Updated commit message with a bit more info... still not link to documentation as there is none :/

**Pull request merged**
